### ISSUE TITLE
CreateAccountRequest 

### ISSUE THREAD

**Issue by tabiszs** [maciejBart99/partyKLINer_docs#2]
Brak klasy CreateAccountRequest

**Comment by JKarchut** [comment]
Tak jak napisałem w specyfikacji, Tworzenie konta będzie realizowane przez azure b2c stąd nie ma potrzeby dokładnego opisywania requestów  z tym związanych. Cała komunikacja będzie się odbywać za pomocą zewnętrznego api (prawdopodobnie biblioteka msal na froncie), a aktualnie zarejestrowani użytkownicy będą pobierani bezpośrednio z b2c. Jedyne elementy związane z użytkownikiem trzymane po stronie bazy danych aplikacji to grafik i filtry dla osoby sprzątającej, zaś te zostały opisane w rozdziale z API
