### ISSUE TITLE
Wyszukiwanie zgłoszeń przez osobę sprzątającą

### ISSUE THREAD

**Issue by tabiszs** [maciejBart99/partyKLINer_docs#3]
Po co jest możliwość wyszukiwania zgłoszeń przez osobę sprzątającą, skoro to organizator przypisuje osobę sprzątającą?

![image](https://user-images.githubusercontent.com/92331225/157531232-02ab161c-f8d3-4ea1-9b09-c786d3f6dfff.png)

**Comment by dkozykowski** [comment]
Osoba sprzątająca deklaruje grafik w których godzinach (wraz z dodatkowymi filtrami) jest chętna do sprzątania i może zdarzyć się tak, że zostanie dopasowana do kilku różnych terminów w kilku różnych miejscach w ramach kilku różnych zamówień.

**Comment by dkozykowski** [comment]
Osoba sprzątająca deklaruje grafik w których godzinach (wraz z dodatkowymi filtrami) jest chętna do sprzątania i może zdarzyć się tak, że zostanie dopasowana do kilku różnych terminów w kilku różnych miejscach w ramach kilku różnych zamówień.

**Comment by JKarchut** [comment]
może to zły dobór słów, chodzi generalnie o możliwość wyświetlenia wszystkich zamówień które mogą zostać zaakceptowane przez osobę sprzątająca
