### ISSUE TITLE
Nieuwzględniony błąd 404 w API

### ISSUE THREAD

**Issue by zh-qs** [maciejBart99/partyKLINer_docs#8]
Opis API nie uwzględnia błędu 404 w razie podania ID nieistniejącego rekordu (w endpointach /orders/{orderId}, /cleaner/{cleanerId}, /cleaner/{cleanerId}/orders, /client/{id}, /user/{id}/*), myślę, że jest to jak najbardziej możliwa sytuacja

**Comment by maciejBart99** [comment]
Wydawało nam się ze zwrot 404 w przypadku rządania o nieistniejące dane jest oczywisty, wiec tak należy taki błąd zwrócić
